{
 "title": "Flask CI/CD App — Ilsa Mukhtar",
 "tags": [
  "flask",
  "cicd",
  "ilsamukhtar"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "App Requests Total",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 6, "h": 4 },
   "targets": [
    { "expr": "app_requests_total", "legendFormat": "Total Requests" }
   ]
  },
  {
   "title": "Pod CPU Usage",
   "type": "graph",
   "gridPos": { "x": 6, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{namespace='flask-app'}[5m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pod Memory Usage",
   "type": "graph",
   "gridPos": { "x": 0, "y": 8, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{namespace='flask-app'}",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}